export const statusOrderGHTK = [
  { code: -1, description: 'Hủy đơn hàng' },
  { code: 1, description: 'Chưa tiếp nhận' },
  { code: 2, description: 'Đã tiếp nhận' },
  { code: 3, description: 'Đã lấy hàng/Đã nhập kho' },
  { code: 4, description: 'Đã điều phối giao hàng/Đang giao hàng' },
  { code: 5, description: 'Đã giao hàng/Chưa đối soát' },
  { code: 6, description: 'Đã đối soát' },
  { code: 7, description: 'Không lấy được hàng' },
  { code: 8, description: 'Hoãn lấy hàng' },
  { code: 9, description: 'Không giao được hàng' },
  { code: 10, description: 'Delay giao hàng' },
  { code: 11, description: 'Đã đối soát công nợ trả hàng' },
  { code: 12, description: 'Đã điều phối lấy hàng/Đang lấy hàng' },
  { code: 13, description: 'Đơn hàng bồi hoàn' },
  { code: 20, description: 'Đang trả hàng (COD cầm hàng đi trả)' },
  { code: 21, description: 'Đã trả hàng (COD đã trả xong hàng)' },
  { code: 123, description: 'Shipper báo đã lấy hàng' },
  { code: 127, description: 'Shipper (nhân viên lấy/giao hàng) báo không lấy được hàng' },
  { code: 128, description: 'Shipper báo delay lấy hàng' },
  { code: 45, description: 'Shipper báo đã giao hàng' },
  { code: 49, description: 'Shipper báo không giao được giao hàng' },
  { code: 410, description: 'Shipper báo delay giao hàng' },
];

export const reasonGHN = [
  { code: 120, description: 'GHTK quá tải, giao không kịp' },
  { code: 121, description: 'Người nhận hàng hẹn giao ca tiếp theo' },
  { code: 122, description: 'Không gọi được cho người nhận hàng' },
  { code: 123, description: 'Người nhận hàng hẹn ngày giao' },
  { code: 124, description: 'Người nhận hàng chuyển địa chỉ nhận mới' },
  { code: 125, description: 'Địa chỉ người nhận sai, cần NCC check lại' },
  { code: 126, description: 'Do điều kiện thời tiết, khách quan' },
  { code: 127, description: 'Lý do khác' },
  { code: 128, description: 'Đối tác hẹn thời gian giao hàng' },
  { code: 129, description: 'Không tìm thấy hàng' },
  { code: 1200, description: 'SĐT người nhận sai, cần NCC check lại' },

  { code: 130, description: 'Người nhận không đồng ý nhận sản phẩm' },
  { code: 131, description: 'Không liên lạc được với KH 3 lần' },
  { code: 132, description: 'KH hẹn giao lại quá 3 lần' },
  { code: 133, description: 'Shop báo hủy đơn hàng' },
  { code: 134, description: 'Lý do khác' },
  { code: 135, description: 'Đối tác hủy đơn qua API' },

  { code: 140, description: 'NCC hẹn trả ca sau' },
  { code: 141, description: 'Không liên lạc được với NCC' },
  { code: 142, description: 'NCC không có nhà' },
  { code: 143, description: 'NCC hẹn ngày trả' },
  { code: 144, description: 'Lý do khác' },
];
