export const messageResponseError = {
  system: {
    missing_data: 'missing_data',
  },
  token: {
    get_token_viettel_error: 'get_token_viettel_error',
  },
  warehouse: {
    warehouse_duplicate: 'warehouse_duplicate',
    warehouse_detail_duplicate: 'warehouse_detail_duplicate',
    warehouse_not_found: 'warehouse_not_found',
  },
  order: {
    payment_method_not_supported: 'payment_method_not_supported',
    config_receive_order_not_supported: 'config_receive_order_not_supported',
    create_order_supership_error: 'create_order_supership_error',
    create_order_viettel_error: 'create_order_viettel_error',
    create_order_ghn_error: 'create_order_ghn_error',
    create_order_nhattin_error: 'create_order_nhattin_error',
    create_order_ghtk_error: 'create_order_ghtk_error',
    missing_quotation_id: 'missing_quotation_id',
    create_order_lalamove_error: 'create_order_lalamove_error',
    unit_not_supported: 'unit_not_supported',
    order_not_found: 'order_not_found',
    cancel_order_ghtk_error: 'cancel_order_ghtk_error',
    viettel_unSupported_print_order: 'viettel_unSupported_print_order',
    cannot_print_order: 'cannot_print_order',
    ship_method_not_supported: 'ship_method_not_supported',
    cancel_order_lalamove_error: 'cancel_order_lalamove_error',
    cancel_order_error: 'cancel_order_error',
    cancel_order_supership_error: 'cancel_order_supership_error',
  },
  webhook: {
    order_not_found: 'order_not_found',
    status_viettel_invalid: 'status_viettel_invalid',
    token_viettel_invalid: 'token_viettel_invalid',
    status_ghtk_invalid: 'status_ghtk_invalid',
    status_nhattin_invalid: 'status_nhattin_invalid',
    status_supership_invalid: 'status_supership_invalid',
    status_ghn_invalid: 'status_ghn_invalid',
    status_lalamove_invalid: 'status_lalamove_invalid',
    api_key_invalid: 'api_key_invalid',
    signature_lalamove_invalid: 'signature_lalamove_invalid',
  },
};
