export const orderStatusViettel = [
  { code: -100, description: 'Đơn hàng mới tạo, chưa duyệt' },
  { code: -108, description: 'Đơn hàng gửi tại bưu cục' },
  { code: -109, description: 'Đơn hàng đã gửi tại điểm thu gom' },
  { code: -110, description: 'Đơn hàng đang bàn giao qua bưu cục' },
  { code: 100, description: 'Tiếp nhận đơn hàng từ đối tác "Viettelpost xử lý đơn hàng"' },
  { code: 101, description: 'ViettelPost yêu cầu hủy đơn hàng' },
  { code: 102, description: 'Đơn hàng chờ xử lý' },
  { code: 103, description: 'Giao cho bưu cục "Viettelpost xử lý đơn hàng"' },
  { code: 104, description: 'Giao cho Bưu tá đi nhận' },
  { code: 105, description: 'Bưu Tá đã nhận hàng' },
  { code: 106, description: 'Đối tác yêu cầu lấy lại hàng' },
  { code: 107, description: 'Đối tác yêu cầu hủy qua API' },
  { code: 200, description: 'Nhận từ bưu tá - Bưu cục gốc' },
  { code: 201, description: 'Hủy nhập phiếu gửi' },
  { code: 202, description: 'Sửa phiếu gửi' },
  { code: 300, description: 'Close delivery file' },
  { code: 301, description: 'Ðóng túi gói "Vận chuyển đi từ"' },
  { code: 302, description: 'Đóng chuyến thư "Vận chuyển đi từ"' },
  { code: 303, description: 'Đóng tuyến xe "Vận chuyển đi từ"' },
  { code: 400, description: 'Nhận bảng kê đến "Nhận tại"' },
  { code: 401, description: 'Nhận Túi gói "Nhận tại"' },
  { code: 402, description: 'Nhận chuyến thư "Nhận tại"' },
  { code: 403, description: 'Nhận chuyến xe "Nhận tại"' },
  { code: 500, description: 'Giao bưu tá đi phát' },
  { code: 501, description: 'Thành công - Phát thành công' },
  { code: 502, description: 'Chuyển hoàn bưu cục gốc' },
  { code: 503, description: 'Hủy - Theo yêu cầu khách hàng' },
  { code: 504, description: 'Thành công - Chuyển trả người gửi' },
  { code: 505, description: 'Tồn - Thông báo chuyển hoàn bưu cục gốc' },
  { code: 506, description: 'Tồn - Khách hàng nghỉ, không có nhà' },
  { code: 507, description: 'Tồn - Khách hàng đến bưu cục nhận' },
  { code: 508, description: 'Phát tiếp' },
  { code: 509, description: 'Chuyển tiếp bưu cục khác' },
  { code: 510, description: 'Hủy phân công phát' },
  { code: 515, description: 'Bưu cục phát duyệt hoàn' },
  { code: 550, description: 'Đơn Vị Yêu Cầu Phát Tiếp' },
];
