export const orderStatusViettel = [
  { code: -100, description: 'Đơn hàng mới tạo, chưa duyệt', statusSys: 'UNPROCESSED' },
  { code: -108, description: 'Đơn hàng gửi tại bưu cục', statusSys: 'RECEIVED' },
  { code: -109, description: 'Đơn hàng đã gửi tại điểm thu gom', statusSys: 'RECEIVED' },
  { code: -110, description: 'Đơn hàng đang bàn giao qua bưu cục', statusSys: 'RECEIVED' },
  { code: 100, description: 'Tiếp nhận đơn hàng từ đối tác "Viettelpost xử lý đơn hàng"', statusSys: 'RECEIVED' },
  { code: 101, description: 'ViettelPost yêu cầu hủy đơn hàng', statusSys: 'CANCEL' },
  { code: 102, description: 'Đơn hàng chờ xử lý', statusSys: 'UNPROCESSED' },
  { code: 103, description: 'Giao cho bưu cục "Viettelpost xử lý đơn hàng"', statusSys: 'RECEIVED' },
  { code: 104, description: 'Giao cho Bưu tá đi nhận', statusSys: 'WAITING_FOR_PICKUP' },
  { code: 105, description: 'Bưu Tá đã nhận hàng', statusSys: 'RECEIVED' },
  { code: 106, description: 'Đối tác yêu cầu lấy lại hàng', statusSys: 'CANCEL' },
  { code: 107, description: 'Đối tác yêu cầu hủy qua API', statusSys: 'CANCEL' },
  { code: 200, description: 'Nhận từ bưu tá - Bưu cục gốc', statusSys: 'RECEIVED' },
  { code: 201, description: 'Hủy nhập phiếu gửi', statusSys: 'UNPROCESSED' },
  { code: 202, description: 'Sửa phiếu gửi', statusSys: 'UNPROCESSED' },
  { code: 300, description: 'Close delivery file', statusSys: 'UNPROCESSED' },
  { code: 301, description: 'Ðóng túi gói "Vận chuyển đi từ"', statusSys: 'RECEIVED' },
  { code: 302, description: 'Đóng chuyến thư "Vận chuyển đi từ"', statusSys: 'RECEIVED' },
  { code: 303, description: 'Đóng tuyến xe "Vận chuyển đi từ"', statusSys: 'RECEIVED' },
  { code: 400, description: 'Nhận bảng kê đến "Nhận tại"', statusSys: 'RECEIVED' },
  { code: 401, description: 'Nhận Túi gói "Nhận tại"', statusSys: 'RECEIVED' },
  { code: 402, description: 'Nhận chuyến thư "Nhận tại"', statusSys: 'RECEIVED' },
  { code: 403, description: 'Nhận chuyến xe "Nhận tại"', statusSys: 'RECEIVED' },
  { code: 500, description: 'Giao bưu tá đi phát', statusSys: 'SHIPPING' },
  { code: 501, description: 'Thành công - Phát thành công', statusSys: 'SHIPPED' },
  { code: 502, description: 'Chuyển hoàn bưu cục gốc', statusSys: 'RETURN' },
  { code: 503, description: 'Hủy - Theo yêu cầu khách hàng', statusSys: 'CANCEL' },
  { code: 504, description: 'Thành công - Chuyển trả người gửi', statusSys: 'RETURN' },
  { code: 505, description: 'Tồn - Thông báo chuyển hoàn bưu cục gốc', statusSys: 'RETURN' },
  { code: 506, description: 'Tồn - Khách hàng nghỉ, không có nhà', statusSys: 'FAILED' },
  { code: 507, description: 'Tồn - Khách hàng đến bưu cục nhận', statusSys: 'RETURN' },
  { code: 508, description: 'Phát tiếp', statusSys: 'SHIPPING' },
  { code: 509, description: 'Chuyển tiếp bưu cục khác', statusSys: 'RECEIVED' },
  { code: 510, description: 'Hủy phân công phát', statusSys: 'RECEIVED' },
  { code: 515, description: 'Bưu cục phát duyệt hoàn', statusSys: 'RETURN' },
  { code: 550, description: 'Đơn Vị Yêu Cầu Phát Tiếp', statusSys: 'SHIPPING' },
];
